version: "3"
services:
  redis:
    image: redis

  db:
    image: postgres:15-alpine

  vote:
    image: voting-app
    ports: 
      - 5000:80
  

  worker:
    image: worker-app
   

  result:
    image: result-app
    ports:
      - 5001:80

